---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: main
    apps.open-cluster-management.io/git-path: book-import
  labels:
    app: book-import
  name: book-import
spec:
    channel: application-samples/gitops
    placement:
      placementRef:
        kind: PlacementRule
        name: book-import-placement-development

---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: main
    apps.open-cluster-management.io/git-path: book-import
  labels:
    app: book-import
  name: book-import-subscription-prod
  namespace: book-import
spec:
    channel: application-samples/gitops
    placement:
      placementRef:
        kind: PlacementRule
        name: book-import-placement-prod

